# Languages

ko:
  languageCode: ko-kr
  languageName: 한국어
  contentDir: content/ko
  title: BAE Research Group
  weight: 1

en:
  languageCode: en-us
  languageName: English
  contentDir: content/en
  weight: 2
  params:
    description: 'BAE Research Group at PNU '
