main:
  - name: 소식
    url: post
    weight: 10
  - name: 구성원
    url: people
    weight: 20
  - name: 연구
    url: research
    weight: 30
  - name: 논문
    url: publication
    weight: 40
  - name: 강의
    url: teaching
    weight: 50
  - name: 연락처
    url: contact
    weight: 60
